spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/dcxt?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  mvc:
    servlet:
      load-on-startup: 1

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.dcxt.bean

server:
  port: 8080
